[package]
name = "winfree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.0"
dioxus-desktop = "0.4.0"
tokio = { version = "1.32.0", features = ["full"] }
windows = { version = "0.51.1", features = [
	"Win32_Foundation",
	"Win32_UI_WindowsAndMessaging",
] }

# [build-dependencies]
# slint-build = "1.2.1"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
